<a href="https://colab.research.google.com/github/balashiva0011/Introduction-to-python-pandas/blob/main/Etl_sql_to_python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### Creating a DataFrame on COVID-19 data can encompass a variety of aspects, such as cases, deaths, recoveries, vaccination rates, etc. Here's an example of how you might structure a DataFrame containing some common COVID-19 metrics for different countries:

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Country': ['USA', 'India', 'Brazil', 'UK', 'France'],
    'Total Cases': [105000000, 45000000, 30000000, 25000000, 25000000],
    'Total Deaths': [1150000, 530000, 650000, 230000, 200000],
    'Total Recoveries': [90000000, 43000000, 20000000, 24000000, 24000000],
    'Vaccination Rate (%)': [78.0, 75.0, 70.0, 85.0, 80.0],
    'Date Reported': ['2024-08-24', '2024-08-24', '2024-08-24', '2024-08-24', '2024-08-24']
}

In [ ]:
df = pd.DataFrame(data)

print(df)

  Country  Total Cases  Total Deaths  Total Recoveries  Vaccination Rate (%)  \
0     USA    105000000       1150000          90000000                  78.0
1   India     45000000        530000          43000000                  75.0
2  Brazil     30000000        650000          20000000                  70.0
3      UK     25000000        230000          24000000                  85.0
4  France     25000000        200000          24000000                  80.0

  Date Reported
0    2024-08-24
1    2024-08-24
2    2024-08-24
3    2024-08-24
4    2024-08-24

In [ ]:
df['Date Reported'] = pd.to_datetime(df['Date Reported'])
df['Date Reported']

0   2024-08-24
1   2024-08-24
2   2024-08-24
3   2024-08-24
4   2024-08-24
Name: Date Reported, dtype: datetime64[ns]

In [ ]:
df = df.dropna()
df

,Country,Total Cases,Total Deaths,Total Recoveries,Vaccination Rate (%),Date Reported
0,USA,105000000,1150000,90000000,78.0,2024-08-24
1,India,45000000,530000,43000000,75.0,2024-08-24
2,Brazil,30000000,650000,20000000,70.0,2024-08-24
3,UK,25000000,230000,24000000,85.0,2024-08-24
4,France,25000000,200000,24000000,80.0,2024-08-24

In [ ]:
def transform_data(df):
    """Transform the data by cleaning and preparing it."""
    df = df.dropna()
    df['Date Reported'] = pd.to_datetime(df['Date Reported'])
    df = df[df['Date Reported'] > '2024-01-01']
    df_summary = df.groupby('Country').agg({
        'Total Cases': 'sum',
        'Total Deaths': 'sum',
        'Total Recoveries': 'sum',
        'Vaccination Rate (%)': 'mean'
    }).reset_index()
    return df_summary

In [ ]:
transformed_data = transform_data(df)
print(transformed_data.head())

  Country  Total Cases  Total Deaths  Total Recoveries  Vaccination Rate (%)
0  Brazil     30000000        650000          20000000                  70.0
1  France     25000000        200000          24000000                  80.0
2   India     45000000        530000          43000000                  75.0
3      UK     25000000        230000          24000000                  85.0
4     USA    105000000       1150000          90000000                  78.0

In [ ]:
int_columns = df.select_dtypes(include=['int64'])
print(int_columns)

# Select columns with object data types
object_columns = df.select_dtypes(include=['object'])
print(object_columns)

   Total Cases  Total Deaths  Total Recoveries
0    105000000       1150000          90000000
1     45000000        530000          43000000
2     30000000        650000          20000000
3     25000000        230000          24000000
4     25000000        200000          24000000
  Country
0     USA
1   India
2  Brazil
3      UK
4  France

In [ ]:
print(df.dtypes)

Country                         object
Total Cases                      int64
Total Deaths                     int64
Total Recoveries                 int64
Vaccination Rate (%)           float64
Date Reported           datetime64[ns]
dtype: object

In [ ]:
!pip install mysql-connector-python

from sqlalchemy import create_engine

def load_data(df):
    engine = create_engine('mysql+mysqlconnector://root:1234@127.0.0.1:3307/employee')
    table_name='employee_2'
    df.to_sql(table_name, engine, if_exists='replace', index=False)
    print(f"Data loaded into {table_name} table in the database.")

load_data(transformed_data)

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (9.0.0)

DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on '127.0.0.1:3307' (111)
(Background on this error at: https://sqlalche.me/e/20/4xp6)